# Generated by Django 4.2.13 on 2025-01-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Город'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Игра'},
        ),
        migrations.AlterModelOptions(
            name='staging',
            options={'verbose_name_plural': 'Прогон'},
        ),
    ]
