# Generated by Django 4.2.13 on 2025-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_alter_city_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='date',
            field=models.DateField(),
        ),
    ]
