# Generated by Django 4.2.13 on 2025-01-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_alter_staging_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Конвент серия',
            },
        ),
        migrations.CreateModel(
            name='ConventStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='executor.city')),
                ('convent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.convent')),
            ],
            options={
                'verbose_name_plural': 'Конвент',
            },
        ),
    ]
