# Generated by Django 4.2.13 on 2025-01-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_convent_conventstaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventstaging',
            name='end_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventstaging',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
