# Generated by Django 4.2.13 on 2025-01-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0005_conventstaging_end_date_conventstaging_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('nickname', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Человек',
            },
        ),
    ]
