# Generated by Django 4.2.13 on 2025-01-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0006_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='staging',
            name='convent_staging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='executor.conventstaging'),
        ),
        migrations.AlterField(
            model_name='staging',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
