# Generated by Django 4.2.13 on 2025-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0007_staging_convent_staging_alter_staging_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventstaging',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
