# Generated by Django 4.2.13 on 2025-01-16 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0008_conventstaging_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Мастерская группа',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='executor.person'),
        ),
        migrations.AddField(
            model_name='game',
            name='short_announcement',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='master_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='executor.mastergroup'),
        ),
    ]
