# Generated by Django 4.2.13 on 2025-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0009_mastergroup_game_author_game_short_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='red_flags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
