# Generated by Django 4.2.13 on 2025-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0010_game_red_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_flags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
