# Generated by Django 4.2.13 on 2025-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0011_alter_game_announcement_alter_game_red_flags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
