# Generated by Django 4.2.13 on 2025-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0012_alter_staging_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
