# Generated by Django 4.2.13 on 2025-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0013_alter_staging_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='convent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staging',
            name='announcement_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
