# Generated by Django 4.2.13 on 2025-01-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0014_convent_description_staging_announcement_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='convent',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastergroup',
            name='vk_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tg_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='vk_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staging',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='executor.person'),
        ),
    ]
