# Generated by Django 5.1.5 on 2025-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0015_convent_url_mastergroup_vk_url_person_tg_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventstaging',
            name='members',
            field=models.ManyToManyField(blank=True, to='executor.person'),
        ),
        migrations.AddField(
            model_name='staging',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='StagingPlayers', to='executor.person'),
        ),
    ]
