# Generated by Django 5.1.5 on 2025-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0017_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventstaging',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='ConventStagingOrganizers', to='executor.person'),
        ),
        migrations.AddField(
            model_name='staging',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='StagingOrganizers', to='executor.person'),
        ),
        migrations.AlterField(
            model_name='staging',
            name='date',
            field=models.DateField(blank=True, default='2025-01-01'),
        ),
        migrations.RemoveField(
            model_name='staging',
            name='master',
        ),
        migrations.AddField(
            model_name='staging',
            name='master',
            field=models.ManyToManyField(blank=True, related_name='StagingMasters', to='executor.person'),
        ),
    ]
