# Generated by Django 5.1.5 on 2025-01-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0018_conventstaging_organizers_staging_organizers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staging',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='StagingTechnicians', to='executor.person'),
        ),
    ]
