# Generated by Django 5.1.5 on 2025-01-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0019_staging_technicians'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staging',
            old_name='master',
            new_name='masters',
        ),
    ]
