# Generated by Django 5.1.5 on 2025-01-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0020_rename_master_staging_masters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Город'},
        ),
    ]
