# Generated by Django 5.1.5 on 2025-01-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0021_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='convent_staging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StagingConvent', to='executor.conventstaging'),
        ),
    ]
