# Generated by Django 5.1.5 on 2025-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0022_alter_staging_convent_staging'),
    ]

    operations = [
        migrations.AddField(
            model_name='staging',
            name='pending_players',
            field=models.ManyToManyField(blank=True, related_name='StagingPendingPlayers', to='executor.person'),
        ),
    ]
